name: Deploy to Firebase

on:
  push:
    branches:
      - main  # mainブランチへのプッシュ時に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Firebaseへデプロイ
      - name: Deploy to Firebase
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}  # GitHub Secretの環境変数を指定
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          python deploy.py  # deploy.pyというファイルでFirebaseへのデプロイを実行
